repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami    

releases:
  - name: postgres
    chart: bitnami/postgresql
    values:
      - ./postgres/values.yaml

  - name: backend
    chart: ./backend
    values:
      - ./backend/values.yaml
    needs:
    - postgres      

  - name: portal
    chart: ./portal
    values:
      - ./portal/values.yaml
    needs:
    - postgres
    - backend         

  - name: adminer
    chart: ./adminer
    values:
      - ./adminer/values.yaml     
    needs:
    - postgres      

  - name: ingress
    chart: ./ingress
    values:
      - ./ingress/values.yaml      
    needs:
    - postgres
    - backend   
    - portal
    - adminer            


