repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami    

releases:
  - name: postgres
    chart: bitnami/postgresql
    values:
      - ./postgres/values.yaml

  - name: backend
    chart: ./backend
    values:
      - ./backend/values.yaml

  - name: portal
    chart: ./portal
    values:
      - ./portal/values.yaml

   - name: adminer
    chart: ./adminer
    values:
      - ./adminer/values.yaml     

  - name: ingress
    chart: ./ingress
    values:
      - ./ingress/values.yaml            


