app:
  name: kanban-app
  group: backend
  replicaCount: 1
  container:
    image: wkrzywiec/kanban-app:k8s
    port: 8080
    config: 
      - name: postgres-config
    env: 
      - key: DB_SERVER
        value: postgres-postgresql.default.svc.cluster.local
  service:
    type: ClusterIP
    port: 8080
  config:
    name: postgres-config
    data:
      - key: POSTGRES_DB
        value: kanban
      - key: POSTGRES_USER
        value: kanban
      - key: POSTGRES_PASSWORD
        value: kanban    
