app:
  name: adminer
  group: db
  replicaCount: 1
  container:
    image: adminer:4.7.6-standalone
    port: 8080
    config: []
    env: 
      - key: ADMINER_DESIGN
        value: pepa-linha
      - key: ADMINER_DEFAULT_SERVER
        value: postgres
  service:
    type: ClusterIP
    port: 8080
