app:
  name: kanban-ui
  group: frontend
  replicaCount: 1
  container:
    image: wkrzywiec/kanban-ui:k8s
    port: 80
    config: []
    env: 
      - key: key
        value: value
  service:
    type: ClusterIP
    port: 8080
